# Generated by Django 5.2 on 2025-06-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='amount_requested',
            new_name='Dependents',
        ),
        migrations.RemoveField(
            model_name='request',
            name='applicant_name',
        ),
        migrations.AddField(
            model_name='request',
            name='ApplicantIncome',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='CoapplicantIncome',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='Credit_History',
            field=models.CharField(choices=[(1, 'YES'), (0, 'NO')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Education',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], default='Graduate', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='LoanAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='Loan_Amount_Term',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='Married',
            field=models.CharField(choices=[(1, 'YES'), (0, 'NO')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Property_Area',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural'), ('Semiurban', 'Semiurban')], default='Urban', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Self_Employed',
            field=models.CharField(choices=[(1, 'YES'), (0, 'NO')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
