# Generated by Django 5.2 on 2025-06-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_rename_amount_requested_request_dependents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Gender',
            field=models.CharField(choices=[(0, 'male'), (1, 'female')], max_length=10),
        ),
    ]
