# Generated by Django 5.2 on 2025-06-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_alter_request_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female')], max_length=10),
        ),
    ]
