# Generated by Django 5.2 on 2025-06-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_alter_request_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Credit_History',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='Married',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='request',
            name='Self_Employed',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], max_length=3),
        ),
    ]
