# Generated by Django 5.2 on 2025-06-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0005_alter_request_credit_history_alter_request_married_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Applicant_Name',
            field=models.CharField(default='Anonymous', max_length=25),
            preserve_default=False,
        ),
    ]
